// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmtLj_X5y_0GrX0km7zI8SYUu_hZzEIBs',
    appId: '1:581583582150:web:5377c9af4e7c4d30cdf8c7',
    messagingSenderId: '581583582150',
    projectId: 'fazaa-car',
    authDomain: 'fazaa-car.firebaseapp.com',
    storageBucket: 'fazaa-car.firebasestorage.app',
    measurementId: 'G-WSCV8ZNB2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwEEDSvbQYp2dx6ncVYV7KcVnLF1ug9U',
    appId: '1:581583582150:android:ef16a6b45313a2ebcdf8c7',
    messagingSenderId: '581583582150',
    projectId: 'fazaa-car',
    storageBucket: 'fazaa-car.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePc0T4bfB_OLb4Nq2sMGkmkNSS3x3ZFg',
    appId: '1:581583582150:ios:17b5a6ef4c76e735cdf8c7',
    messagingSenderId: '581583582150',
    projectId: 'fazaa-car',
    storageBucket: 'fazaa-car.firebasestorage.app',
    iosBundleId: 'com.example.fazaaCar',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePc0T4bfB_OLb4Nq2sMGkmkNSS3x3ZFg',
    appId: '1:581583582150:ios:17b5a6ef4c76e735cdf8c7',
    messagingSenderId: '581583582150',
    projectId: 'fazaa-car',
    storageBucket: 'fazaa-car.firebasestorage.app',
    iosBundleId: 'com.example.fazaaCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmtLj_X5y_0GrX0km7zI8SYUu_hZzEIBs',
    appId: '1:581583582150:web:1b555259a5d819e6cdf8c7',
    messagingSenderId: '581583582150',
    projectId: 'fazaa-car',
    authDomain: 'fazaa-car.firebaseapp.com',
    storageBucket: 'fazaa-car.firebasestorage.app',
    measurementId: 'G-ZENG001VM6',
  );
}
